// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdWMm67xDURyeacSjo1g-zOT9HNnX83lI',
    appId: '1:59544886386:android:a758a09b88637c2882f6eb',
    messagingSenderId: '59544886386',
    projectId: 'hafilaty-driver',
    storageBucket: 'hafilaty-driver.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9RDIJAYUCKZbej3U5ttpmWAfSadx5QYg',
    appId: '1:59544886386:web:cb664dc862bf245e82f6eb',
    messagingSenderId: '59544886386',
    projectId: 'hafilaty-driver',
    authDomain: 'hafilaty-driver.firebaseapp.com',
    storageBucket: 'hafilaty-driver.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABC_I0gEoR5z5A6-C-Fm6CBMetrAtZ6Fo',
    appId: '1:59544886386:ios:41d23088f74cc5eb82f6eb',
    messagingSenderId: '59544886386',
    projectId: 'hafilaty-driver',
    storageBucket: 'hafilaty-driver.firebasestorage.app',
    iosBundleId: 'dev.hyderali.trippodriver',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABC_I0gEoR5z5A6-C-Fm6CBMetrAtZ6Fo',
    appId: '1:59544886386:ios:41d23088f74cc5eb82f6eb',
    messagingSenderId: '59544886386',
    projectId: 'hafilaty-driver',
    storageBucket: 'hafilaty-driver.firebasestorage.app',
    iosBundleId: 'dev.hyderali.trippodriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9RDIJAYUCKZbej3U5ttpmWAfSadx5QYg',
    appId: '1:59544886386:web:d7221a70f757253682f6eb',
    messagingSenderId: '59544886386',
    projectId: 'hafilaty-driver',
    authDomain: 'hafilaty-driver.firebaseapp.com',
    storageBucket: 'hafilaty-driver.firebasestorage.app',
  );

}